### ISSUE TITLE
Drupal

### ISSUE THREAD

**Issue by lpalgarvio** [heldergg/dre#1]
Boas

Antes de mais, excelente trabalho!!! Faz falta a existência de pessoas que questionem e desafiem os estados que se fecham e ocultam / dificultam o acesso a informação.

Pergunta, já ponderaste uma versão em Drupal?

O Drupal 8 está quase em fase de lançamento e vem preparado de raiz para PHP 5.5 e usa Symfony 2.

Cumps

**Comment by vickyaditya** [comment]
Emm can you translate your language to english sir? theres many translation who not match (not translate) thanks

**Comment by lpalgarvio** [comment]
Hello,

Sorry, i thought you spoke portuguese. I0ll rephrase,

I meant to say that you did an excellent marvelous work! We miss this kind of initiatives and people that question the states and governments that deliberately silent, occult and make difficult the access to information.

My question was,
Have you considered building a version of this code with Drupal 7 or 8 (and PHP)?

Drupal 8 is being launched soon and comes prepared for PHP 5.5 and uses Symfony 2.

Best regards

**Comment by rlafuente** [comment]
I'm not the author, but I feel compelled to point that the Django-based site works well as it is. 

I'm not sure what the advantages of rewriting the site on a different framework would be, as shiny as Drupal 8 can be -- and Drupal is infamous for its disregard for backwards compatibility on new versions, unlike Django.

**Comment by j1fig** [comment]
Hi. I've recently watched this repo, and I also don't see any added value of supporting another framework.

I feel this works quite well as a single, monolithic app, that does well what is says it does.

**Comment by heldergg** [comment]
> Pergunta, já ponderaste uma versão em Drupal?
> O Drupal 8 está quase em fase de lançamento e vem preparado de raiz para PHP 5.5 e usa Symfony 2.

Não pá! Faço isto como hobby. Isto em PHP era mais parecido com castigo! ;-) 

Estou a brincar, no entanto, mudar de plataforma equivaleria a recomeçar do inicio. Não vou fazer isso.

**Comment by heldergg** [comment]
Bom, isto é software livre. Se pensares numa API podes implementa-la e fazer um PR. Não prometo que a inclua no site que está no ar, assim, se quiseres garantir isso mostra-me primeiro o que pretendes. Em todo o caso, neste momento, já podes ir buscar os meta dados de cada documento, basta acrescentar ".json" ao respectivo url. Por exemplo:

* https://dre.tretas.org/dre/2735631.json

Como disse, não é prioridade neste momento para mim.
